// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVC1Xu_6_WtKxRsFdlpMlwMn-98lXIWV0',
    appId: '1:458328862106:web:bd2393c8a2b40c6f435e23',
    messagingSenderId: '458328862106',
    projectId: 'chat2-ef4ee',
    authDomain: 'chat2-ef4ee.firebaseapp.com',
    storageBucket: 'chat2-ef4ee.appspot.com',
    measurementId: 'G-ZKX0CSR9ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWAWC02NxNYpFlh-rCl7AFZnGxx-52r2M',
    appId: '1:458328862106:android:8c96b52bb331bc8b435e23',
    messagingSenderId: '458328862106',
    projectId: 'chat2-ef4ee',
    storageBucket: 'chat2-ef4ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-4wfoeFJjtF0aMiHLZxL-f3F4SjFyRNI',
    appId: '1:458328862106:ios:f94d3753ff67ef97435e23',
    messagingSenderId: '458328862106',
    projectId: 'chat2-ef4ee',
    storageBucket: 'chat2-ef4ee.appspot.com',
    iosClientId: '458328862106-i27kef8v5r3019ijkf7cq3h0l04j4p3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-4wfoeFJjtF0aMiHLZxL-f3F4SjFyRNI',
    appId: '1:458328862106:ios:d8cebd7c4402440d435e23',
    messagingSenderId: '458328862106',
    projectId: 'chat2-ef4ee',
    storageBucket: 'chat2-ef4ee.appspot.com',
    iosClientId: '458328862106-eofajsf2guqkud7nfldhtfmnkj1omli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
